import { Metadata } from "next";

const TITLE = "Create Next App";
const DESCRIPTION = "Generated by create next app";

export const siteConfig: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
};